/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.rl235;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.Reader;

public class App {

  private final Board<Character> theBoard;

  private final BoardTextView view;

  private final BufferedReader inputReader;

  private final PrintStream out;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {

    // BufferedReader

    //BattleShipBoard<Character>(10,20);
    // this.theBoard = new Board(10, 20);

    // this.view = new BoardTextView(theBoard);
    // this.inputReader = new BufferedReader(new InputStreamReader(System.in));
    // this.out = System.out;

    this.theBoard = theBoard;

    this.view = new BoardTextView(theBoard);

    this.inputReader = new BufferedReader(inputSource);

    this.out = out;//!interesting!

  }

  public Placement readPlacement(String prompt) throws IOException {

    out.println(prompt);

    String s = inputReader.readLine();

    return new Placement(s);

  }

  public void doOnePlacement() throws IOException {

    String prompt = "Where would you like to put your ship?";

    Placement p = readPlacement(prompt);

    Coordinate c = p.getCoordinate();

    Ship<Character> s = new BasicShip(c);

    theBoard.tryAddShip(s);

    out.println(view.displayMyOwnBoard()); // meaning?

  }
  
  

  public static void main(String[] args) throws IOException {

    Board<Character> b= new BattleShipBoard<Character>(10, 20);
    
    App a = new App(b, new InputStreamReader(System.in), System.out);

    a.doOnePlacement();

  }
  
}
