/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.rl235;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.StringReader;



public class App {

  private final TextPlayer player1;

  private final TextPlayer player2;






  public App(TextPlayer p1, TextPlayer p2){
    
    this.player1 = p1;
    this.player2 = p2;
    
  }

  //private final AbstractShipFactory<Character> shipFactory;

  // private final Board<Character> theBoard;

  //private final BoardTextView view;

  //private final BufferedReader inputReader;

  //private final PrintStream out;

  
  //public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {


    //// BufferedReader

    ////BattleShipBoard<Character>(10,20);
    ////this.theBoard = new Board(10, 20);

    //// this.view = new BoardTextView(theBoard);
    //// this.inputReader = new BufferedReader(new InputStreamReader(System.in));
    //// this.out = System.out;

    //this.shipFactory = new V1ShipFactory();//need this constructor to implement
    
    //this.theBoard = theBoard;

    //this.view = new BoardTextView(theBoard);

    //this.inputReader = new BufferedReader(inputSource);

    //this.out = out;//!interesting!!
  //}


  
  //readPlacement!
  //public Placement readPlacement(String prompt) throws IOException {

  //out.println(prompt);

  //String s = inputReader.readLine();

  //return new Placement(s);//will throw if invalid orientation!

  //}

  
  //doOnePlacement!
  //public void doOnePlacement() throws IOException {

  //String prompt = "Where would you like to put your ship?";

  //Placement p = readPlacement(prompt);

    ////Coordinate c = p.getCoordinate();

    ////Ship<Character>  s = new BasicShip<Character>(c);
    
    ////Ship<Character> s = new RectangleShip<Character>(c, 's', '*');

    //Ship<Character> s  = shipFactory.makeDestroyer(p);

    //theBoard.tryAddShip(s);
    //s.recordHitAt(new Coordinate("Q4"));


    //out.println(view.displayMyOwnBoard()); // meaning?print write to out
  //}


  public void doPlacementPhase() throws IOException{

    //player1.doOnePlacement();
    player1.doPlacementPhase();
    player2.doPlacementPhase();

    
  }

  public void doAttackingPhase(Board<Character> p1Board, Board<Character> p2Board,BoardTextView myView, BoardTextView enView) throws IOException{

    TextPlayer currentPlayer = player1;
    TextPlayer otherPlayer = player2;
    
    Board<Character> currentBoard = p1Board;
    Board<Character> otherBoard = p2Board;

    BoardTextView currentView = myView;
    BoardTextView otherView = enView;

    
    String currentHeader = "Player A's Ocean";
    String otherHeader = "Player B's Ocean";
    
    
    while (true) {
      String message = currentPlayer.playOneTurn(otherBoard, otherView, "Your Ocean", otherHeader);
      
      System.out.println(message);
      
      if (otherBoard.check_lost()) {

        System.out.println("Player " + currentPlayer.getName() + " wins!");
        
        //return "Player " + currentPlayer.getName() + " wins!";
        return;
        
      }
   //swap current and other player for next time around loop
   TextPlayer temp1 = currentPlayer;
   currentPlayer = otherPlayer;
   otherPlayer = temp1;

   
   Board<Character> temp2 = otherBoard;
   otherBoard = currentBoard;
   currentBoard = temp2;

   BoardTextView temp3 = otherView;
   otherView = currentView;
   currentView = temp3;

   String temp4 = otherHeader;
   otherHeader = currentHeader;
   currentHeader = temp4;
   
    }


  }

  private static String doModeChoosePhase(BufferedReader inputReader, PrintStream out) throws IOException {
    
    String prompt = "There are four modes of this game, please enter the corresponding number to play with:\n" +
    "1. Human vs Human\n" + 
    "2. Human vs Computer\n" + 
    "3. Computer vs Human\n" + 
    "4. Computer vs Computer\n";
    out.println(prompt);

    String s = inputReader.readLine();
    return s;
  }
  
  
  public static String iterateBoard(Board<Character> board){
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < board.getHeight(); i++){
      for (int j = 0; j < board.getWidth(); j++){
        sb.append((char)('a' + i) + Integer.toString(j) + "\n");
      }
    }
    return sb.toString();
  }
  
  
  //independent of all classes, used for testing!
  public static void main(String[] args) throws IOException {

    //Board<Character> b= new BattleShipBoard<Character>(10, 20);
    
    //App a = new App(b, new InputStreamReader(System.in), System.out);

    //a.doOnePlacement();

    //String computerInput = "a0v\na1v\na2v\na3v\na4v\na5l\na7l\ne0l\nO0l\ns0l\n";

    //BufferedReader computeReader = new BufferedReader(new StringReader(computerInput));
    

    Board<Character> b1 = new BattleShipBoard<>(10, 20, 'X');

    Board<Character> b2 = new BattleShipBoard<>(10, 20, 'X');

    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));

     PrintStream out = System.out;

     //String computerInput = "a0v\na1v\na2v\na3v\na4v\ne0r\ne5l\nh0r\nO5r\ni6d\n" + iterateBoard(b1);

     String computerInput = "a0v\na1v\nO5r\ni6d\n" + iterateBoard(b1);

    BufferedReader computeReader = new BufferedReader(new StringReader(computerInput));
    BufferedReader computeReader2 = new BufferedReader(new StringReader(computerInput));


    //V1ShipFactory factory = new V1ShipFactory();

    V2ShipFactory factory = new V2ShipFactory();

    TextPlayer p1;
    TextPlayer p2;


    //TextPlayer p1 = new TextPlayer(3, 3, "A", b1, input, System.out, factory);

    //TextPlayer p2 = new TextPlayer(3, 3, "B", b2, input, System.out, factory);

    

    String mode = doModeChoosePhase(input, out);


    if (mode.equals("1")){
      
      p1 = new TextPlayer(3, 3, "A", b1, input, System.out, factory);
      p2 = new TextPlayer(3, 3, "B", b2, input, System.out, factory);
      
    }

    else if (mode.equals("2")){
      p1 = new TextPlayer(3, 3, "A", b1, input, System.out, factory);
      p2 = new ComputerPlayer(3, 3, "Computer B", b2, computeReader, System.out, factory);
      
      
    }

    else if (mode.equals("3")){
      p1 = new ComputerPlayer(3, 3, "Computer A", b1, computeReader, System.out, factory);
      p2 = new TextPlayer(3, 3, "B", b2, input, System.out, factory);
      
      
    }

    else{
      p1 = new ComputerPlayer(3, 3, "Computer A", b1, computeReader, System.out, factory);
      p2 = new ComputerPlayer(3, 3, "Computer B", b2, computeReader2, System.out, factory);
      
      
    }

    

    App a = new App(p1, p2);

   
    a.doPlacementPhase();//player 1&2 doOnePlacement!

    BoardTextView p1View = new BoardTextView(b1);

    BoardTextView p2View = new BoardTextView(b2);
    

    a.doAttackingPhase(b1, b2, p1View, p2View);

    

    
    

  }
  
}
