/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.rl235;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import java.io.PrintStream;
import java.io.Reader;



public class App {

  private final TextPlayer player1;

  private final TextPlayer player2;






  public App(TextPlayer p1, TextPlayer p2){
    
    this.player1 = p1;
    this.player2 = p2;
    
  }

  //private final AbstractShipFactory<Character> shipFactory;

  // private final Board<Character> theBoard;

  //private final BoardTextView view;

  //private final BufferedReader inputReader;

  //private final PrintStream out;

  
  //public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {


    //// BufferedReader

    ////BattleShipBoard<Character>(10,20);
    ////this.theBoard = new Board(10, 20);

    //// this.view = new BoardTextView(theBoard);
    //// this.inputReader = new BufferedReader(new InputStreamReader(System.in));
    //// this.out = System.out;

    //this.shipFactory = new V1ShipFactory();//need this constructor to implement
    
    //this.theBoard = theBoard;

    //this.view = new BoardTextView(theBoard);

    //this.inputReader = new BufferedReader(inputSource);

    //this.out = out;//!interesting!!
  //}


  
  //readPlacement!
  //public Placement readPlacement(String prompt) throws IOException {

  //out.println(prompt);

  //String s = inputReader.readLine();

  //return new Placement(s);//will throw if invalid orientation!

  //}

  
  //doOnePlacement!
  //public void doOnePlacement() throws IOException {

  //String prompt = "Where would you like to put your ship?";

  //Placement p = readPlacement(prompt);

    ////Coordinate c = p.getCoordinate();

    ////Ship<Character>  s = new BasicShip<Character>(c);
    
    ////Ship<Character> s = new RectangleShip<Character>(c, 's', '*');

    //Ship<Character> s  = shipFactory.makeDestroyer(p);

    //theBoard.tryAddShip(s);
    //s.recordHitAt(new Coordinate("Q4"));


    //out.println(view.displayMyOwnBoard()); // meaning?print write to out
  //}


  public void doPlacementPhase() throws IOException{

    //player1.doOnePlacement();
    player1.doPlacementPhase();
    player2.doPlacementPhase();

    
  }

  public void doAttackingPhase(Board<Character> p1Board, Board<Character> p2Board,BoardTextView myView, BoardTextView enView) throws IOException{

    TextPlayer currentPlayer = player1;
    TextPlayer otherPlayer = player2;
    
    Board<Character> currentBoard = p1Board;
    Board<Character> otherBoard = p2Board;

    BoardTextView currentView = myView;
    BoardTextView otherView = enView;

    
    String currentHeader = "Player A's Ocean";
    String otherHeader = "Player B's Ocean";
    
    
    while (true) {
      String message = currentPlayer.playOneTurn(otherBoard, otherView, "Your Ocean", otherHeader);
      
      System.out.println(message);
      
      if (otherBoard.check_lost()) {

        System.out.println("Player " + currentPlayer.getName() + " wins!");
        
        //return "Player " + currentPlayer.getName() + " wins!";
        return;
        
      }
   //swap current and other player for next time around loop
   TextPlayer temp1 = currentPlayer;
   currentPlayer = otherPlayer;
   otherPlayer = temp1;

   
   Board<Character> temp2 = otherBoard;
   otherBoard = currentBoard;
   currentBoard = temp2;

   BoardTextView temp3 = otherView;
   otherView = currentView;
   currentView = temp3;

   String temp4 = otherHeader;
   otherHeader = currentHeader;
   currentHeader = temp4;
   
    }


  }

  
  
  
  
  //independent of all classes, used for testing!
  public static void main(String[] args) throws IOException {

    //Board<Character> b= new BattleShipBoard<Character>(10, 20);
    
    //App a = new App(b, new InputStreamReader(System.in), System.out);

    //a.doOnePlacement();


    Board<Character> b1 = new BattleShipBoard<>(10, 20, 'X');

    Board<Character> b2 = new BattleShipBoard<>(10, 20, 'X');

    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));

    V1ShipFactory factory = new V1ShipFactory();

    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);

    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);

    App a = new App(p1, p2);

   
    a.doPlacementPhase();//player 1&2 doOnePlacement!

    BoardTextView p1View = new BoardTextView(b1);

    BoardTextView p2View = new BoardTextView(b2);
    

    a.doAttackingPhase(b1, b2, p1View, p2View);

    

    
    

  }
  
}
